# Site/SEO settings
email: crissellecm@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Crisselle Mendiola
title: Crisselle Mendiola
description: 
url: http://crissellemendiola.com
default_img: /assets/images/contactpic.jpg
social:
  - name: instagram
    url: https://www.instagram.com/crissellem/

# Contact settings
contact_img: /assets/images/contactpic.jpg
formcarry: https://formcarry.com/s/X1tZqdDrNW9

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Crisselle Mendiola
    bio: Crisselle is an illustrator based in Southern California. Her work primarily deals with expressing emotions and feelings, which can be seen through her characters. As these illustrations are usually character driven, she aims to tell a story and let people who view her work relate to it or empathize with it. Sometimes these pieces are lighthearted and fun and other times they are not. But either way, these feelings are shown through her distinct style.
    url: http://crissellemendiola.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
